### ISSUE TITLE
Mise en place de dependabot ?

### ISSUE THREAD

**Issue by NicolasGrosjean** [CartONG/SOSMedDashboard#26]
J'ai récemment corrigé des vulnérabilités en mettant à jour nos dépendances à la main (cb99174).

Est-ce qu'on n'automatiserait pas ça avec [dependabot ](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) comme c'est le cas avec le [Dashboard des Mapathons](https://github.com/CartONG/mapathon_dashboard) ?

**Comment by CartONG-staff** [comment]
Je suis plutôt pour.

**Comment by etienne-cartong** [comment]
Je suis assez pour. 
J'ai activé "Dependabot security updates". Il me semble que la config par défaut suffit non ? Si oui, c'est réglé.
