### ISSUE TITLE
Update SAR data

### ISSUE THREAD

**Issue by NicolasGrosjean** [CartONG/SOSMedDashboard#42]
- [x] Ask for new SAR data (Maëlle)
- [x] Add SAR data to the dashboard

**Comment by NicolasGrosjean** [comment]
I used [this tutorial](https://docs.mapbox.com/mapbox-gl-js/example/geojson-polygon/) to do ef811065a45eed5c5a437cd598d42208a036e095

![image](https://user-images.githubusercontent.com/13560473/221212913-4b36deb1-558e-4a86-9a76-bada91889de0.png)

**Comment by NicolasGrosjean** [comment]
With feedbacks from @damiendevienne implemented in b661e014ca1d805dbb097c64921532a1e9b7faaf

![image](https://user-images.githubusercontent.com/13560473/221235029-bb310087-e4a9-48d3-8100-89845a904ee8.png)

**Comment by regazzoj** [comment]
@NicolasGrosjean I can see that there is an other checkbox on your todo list.
What is it about ?

**Comment by NicolasGrosjean** [comment]
> @NicolasGrosjean I can see that there is an other checkbox on your todo list. What is it about ?

I mixed up new data and SAR data.
I corrected and checked the 2nd line

**Comment by regazzoj** [comment]
For me, it's fine the way you did and you can close it whenever you want.
Maybe a feedback from @damiendevienne could be nice (:

**Comment by damiendevienne** [comment]
Its' great! 
Three questions, though: 
- do you think people will understand that the text "RCC ..." refer to the zones delimited by the dashed lines? If not, an option is to put this text along the lines insider the zones. 
- Are the names (RCC ...) the most informative ones ? On some websites it's written "Maltese SRR","Italien SRR", etc. Maybe we should ask SOSmed directly
- Is there a button to show/hide these zones?

**Comment by NicolasGrosjean** [comment]
> do you think people will understand that the text "RCC ..." refer to the zones delimited by the dashed lines? If not, an option is to put this text along the lines insider the zones.

Yes it is possible, it was my first draft before you advise me to change for the center.
In fact the limits between the area are shared by them so it is not very understable.

![image](https://user-images.githubusercontent.com/13560473/231530230-fc57b356-934e-422f-9f7b-d6af20976162.png)


>  Are the names (RCC ...) the most informative ones ? On some websites it's written "Maltese SRR","Italien SRR", etc. Maybe we should ask SOSmed directly

It is easy to change. I think it is a good idea to ask to SOSmed because I don't know what this the term the most used (except doing some stats with result number in Google).

>  Is there a button to show/hide these zones?

Not currently, but we can add it. 
I have few time this week.
@regazzoj have you more time and do you want implement it ?

**Comment by regazzoj** [comment]
I am adding a button to show/hide these zones.

**Comment by regazzoj** [comment]
@NicolasGrosjean I added a switch button for SAR. Close the PR if you think that it is enough (:

**Comment by NicolasGrosjean** [comment]
Implemented by #49
